language: php

services:
  - redis-server
  - mongodb

php:
  - 5.4
  - 5.5
  - 5.6

cache:
  directories:
    - ~/.composer/cache

env:
  - MONGO_REPO="http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen"
  - MONGO_REPO="http://repo.mongodb.org/apt/ubuntu $(lsb_release -sc)/mongodb-org/3.0 multiverse"

matrix:
  fast_finish: true

before_install:
  - printf "\n" |pecl install imagick
  - phpenv config-add .travis.php.ini
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo "deb ${MONGO_REPO}" | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update

install:
  - sudo apt-get install mongodb-org-server
  - composer install --prefer-dist

before_script:
  - sudo mkdir -p /var/uploaded-files && sudo chmod -R a+w /var/uploaded-files
  - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
  - php app/console orchestra:mongodb:fixtures:load --type=functional -e=test

script:
  - phpunit -c app/ --testsuite=unit
  - phpunit -c app/ --group integrationTest
  - phpunit -c app/ --group media
  - phpunit -c app/ --group securityCheck
  - phpunit -c app/ --group apiFunctional
