language: php

php:
  - 5.4

cache:
  directories:
    - ~/.composer/cache

sudo: false

before_install:
  - phpenv config-add .travis.php.ini

install:
  - composer install --no-progress --prefer-dist

script: ./bin/phpunit

after_script:
  - CODECLIMATE_REPO_TOKEN=2b1aac8bcb3be2b2d1d469d40877fdef2fcaf3d288b9a738b719f65ac193f8c0 ./bin/test-reporter
