language: php

services:
  - redis-server
  - mongodb

php:
  - 5.4

sudo: false

before_install:
  - printf "\n" |pecl install imagick
  - phpenv config-add .travis.php.ini

install:
  - composer install

before_script:
  - php app/console doc:mo:f:l -e=test

script: phpunit -c app/
