resolve_target_documents:
        OpenOrchestra\WorkflowFunction\Model\WorkflowFunctionInterface: OpenOrchestra\WorkflowFunctionBundle\Document\WorkflowFunction
        OpenOrchestra\WorkflowFunction\Model\AuthorizationInterface: OpenOrchestra\WorkflowFunctionBundle\Document\Authorization
        OpenOrchestra\WorkflowFunction\Model\ReferenceInterface: OpenOrchestra\WorkflowFunctionBundle\Document\Reference
