parameters:
    open_orchestra_workflow_function_admin.type.role_choice.class: OpenOrchestra\WorkflowFunctionModelBundle\Form\Type\RoleType

services:
    open_orchestra_workflow_function_admin.type.role_choice:
        class: %open_orchestra_workflow_function_admin.type.role_choice.class%
        arguments:
            - %open_orchestra_model.document.role.class%
            - @open_orchestra_model.repository.role
        tags:
            - { name: form.type, alias: role_choice}
