monolog:
    handlers:
        main:
            type: stream
            level: 200
            channels: phporchestra
            handler: mongo
        mongo:
            type: mongo
            level: 200
            mongo:
                host: "localhost"
                database: "%php_orchestra_cms.mongodb.database%"
                collection: log
            channels: phporchestra
