php_orchestra_backoffice:
    resource: "@PHPOrchestraBackofficeBundle/Controller"
    type: annotation
    prefix: /admin

php_orchestra_user:
    resource: "@PHPOrchestraUserBundle/Controller"
    type: annotation
    prefix: /admin

php_orchestra_display:
    resource: "@PHPOrchestraDisplayBundle/Controller"
    type: annotation

php_orchestra_api:
    resource: "@PHPOrchestraApiBundle/Controller"
    type: annotation
    prefix: /api

php_orchestra_log:
    resource: "@PHPOrchestraLogBundle/Controller"
    type: annotation
    prefix: /api

php_orchestra_media:
    resource: "@PHPOrchestraMediaBundle/Controller"
    type: annotation
    prefix: /media

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin
        permanent: true
