parameters:
    open_orchestra_workflow_function_admin.navigation_panel.workflow_function.class: OpenOrchestra\WorkflowFunctionAdminBundle\NavigationPanel\Strategies\WorkflowFunctionPanelStrategy

services:
    open_orchestra_workflow_function_admin.navigation_panel.workflow_function:
        class: %open_orchestra_workflow_function_admin.navigation_panel.workflow_function.class%
        tags:
            - { name: open_orchestra_backoffice.navigation_panel.strategy }
