php_orchestra_theme:
    themes: 
        sample:
            name: "Native example"
            stylesheets:
                - PHPOrchestraThemeBundle:sample:css/master.css
                - PHPOrchestraThemeBundle:sample:css/fo.css
        theme1:
            name: "Theme \#1"
            stylesheets :
                - FakeAppThemeBundle:theme1:css/master.css
                - FakeAppThemeBundle:theme1:css/main.css
                - FakeAppThemeBundle:theme1:css/secondly.css
            javascripts :
                - PHPOrchestraThemeBundle:theme1:js/empty.js
        theme2:
            name: "Theme \#2"
            stylesheets :
                - FakeAppThemeBundle:theme2:css/another.css
                - FakeAppThemeBundle:theme2:css/custom.css
                - FakeAppThemeBundle:theme2:css/master.css
        fromApp:
            name: "Theme from app"
            stylesheets :
                - FakeAppThemeBundle:fromApp:css/master.css
            javascripts :
                - FakeAppThemeBundle:fromApp:js/js.js
                - FakeAppThemeBundle:fromApp:js/subfolder/sub.js
        mixed:
            name: "Theme mixing several other themes"
            stylesheets :
                - PHPOrchestraThemeBundle:sample:css/fo.css
                - FakeAppThemeBundle:theme2:css/main.css
            javascripts :
                - PHPOrchestraThemeBundle:theme1:js/empty.js
                - FakeAppThemeBundle:fromApp:js/subfolder/sub.js
 