php_orchestra_backoffice:
    resource: "@PHPOrchestraBackofficeBundle/Controller"
    type: annotation
    prefix: /admin

php_orchestra_user:
    resource: "@PHPOrchestraUserBundle/Controller"
    type: annotation
    prefix: /user

php_orchestra_display:
    resource: "@PHPOrchestraDisplayBundle/Controller"
    type: annotation

php_orchestra_api:
    resource: "@PHPOrchestraApiBundle/Controller"
    type: annotation
    prefix: /api

php_orchestra_indexation:
    resource: "@PHPOrchestraIndexationBundle/Controller"
    type: annotation

php_orchestra_translation:
    resource: "@PHPOrchestraTranslationBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin
        permanent: true
