php_orchestra_cms:
    resource: "@PHPOrchestraCMSBundle/Resources/config/routing.yml"
    prefix:   /

php_orchestra_front:
    resource: "@PHPOrchestraFrontBundle/Controller"
    type: annotation

php_orchestra_display:
    resource: "@PHPOrchestraDisplayBundle/Controller"
    type: annotation

php_orchestra_api:
    resource: "@PHPOrchestraApiBundle/Resources/config/routing.yml"
    prefix: /api

php_orchestra_indexation:
    resource: "@PHPOrchestraIndexationBundle/Controller"
    type: annotation
