php_orchestra_backoffice:
    resource: "@PHPOrchestraBackofficeBundle/Controller"
    type: annotation
    prefix: /admin

php_orchestra_display:
    resource: "@PHPOrchestraDisplayBundle/Controller"
    type: annotation

php_orchestra_api:
    resource: "@PHPOrchestraApiBundle/Controller"
    type: annotation
    prefix: /api

php_orchestra_indexation:
    resource: "@PHPOrchestraIndexationBundle/Controller"
    type: annotation
