---
download_url: http://selenium-release.storage.googleapis.com/{{directory_version}}/{{jar_file}}
jar_file: selenium-server-standalone-{{server_version}}.jar
server_version: 2.44.0
directory_version: 2.44
cur_dir: /home/vagrant
driver_version: 2.9
download_driver: http://chromedriver.storage.googleapis.com/{{driver_version}}/{{driver}}
driver: "{{driver_exec}}_linux64.zip"
driver_exec: chromedriver
selenium_dir: /usr/local/lib


sel_role: standalone

hub: ''
java_opts: ''
extra_args: -Dwebdriver.chrome.driver={{cur_dir}}/  {{driver_exec}}
port: ''