- src: geerlingguy.php
  version: 1.2.9

#- src: DavidWittman.redis
#  version: 1.0.2

- src: geerlingguy.varnish
  version: 1.1.1

- src: geerlingguy.java
  version: 1.0.4

- src: JasonGiedymin.nodejs
  version: master

- src: ThePixelDeveloper.google-chrome
  version: master
