---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
  sudo: yes
  pre_tasks:
    - name: Check php conf directory
      stat: path=/etc/php5/conf.d
      register: php_conf_directory
    - name: Create a directory for php conf
      shell: mkdir -p /etc/php5/conf.d
      when: php_conf_directory.stat.exists == false
  roles:
    - php
    - web
    - databases
    - git
    - selenium
    - orchestraCron
