---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
  remote_user: vagrant
  sudo: yes
  pre_tasks:
    - name: Create a directory for php conf
      shell: mkdir -p /etc/php5/conf.d
  roles:
    - DavidWittman.redis
    - lesmyrmidons.mongodb
    - php
    - web
    - solr
